/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheoryRouteImport } from './routes/theory'
import { Route as TestRouteImport } from './routes/test'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as SvedenRouteImport } from './routes/sveden'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinalTestRouteImport } from './routes/final-test'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'

const TheoryRoute = TheoryRouteImport.update({
  id: '/theory',
  path: '/theory',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const SvedenRoute = SvedenRouteImport.update({
  id: '/sveden',
  path: '/sveden',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalTestRoute = FinalTestRouteImport.update({
  id: '/final-test',
  path: '/final-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/documents': typeof DocumentsRoute
  '/final-test': typeof FinalTestRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/sveden': typeof SvedenRoute
  '/teacher': typeof TeacherRoute
  '/test': typeof TestRoute
  '/theory': typeof TheoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/documents': typeof DocumentsRoute
  '/final-test': typeof FinalTestRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/sveden': typeof SvedenRoute
  '/teacher': typeof TeacherRoute
  '/test': typeof TestRoute
  '/theory': typeof TheoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/documents': typeof DocumentsRoute
  '/final-test': typeof FinalTestRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/programs': typeof ProgramsRoute
  '/register': typeof RegisterRoute
  '/sveden': typeof SvedenRoute
  '/teacher': typeof TeacherRoute
  '/test': typeof TestRoute
  '/theory': typeof TheoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/ai'
    | '/documents'
    | '/final-test'
    | '/login'
    | '/map'
    | '/programs'
    | '/register'
    | '/sveden'
    | '/teacher'
    | '/test'
    | '/theory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/ai'
    | '/documents'
    | '/final-test'
    | '/login'
    | '/map'
    | '/programs'
    | '/register'
    | '/sveden'
    | '/teacher'
    | '/test'
    | '/theory'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/ai'
    | '/documents'
    | '/final-test'
    | '/login'
    | '/map'
    | '/programs'
    | '/register'
    | '/sveden'
    | '/teacher'
    | '/test'
    | '/theory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AiRoute: typeof AiRoute
  DocumentsRoute: typeof DocumentsRoute
  FinalTestRoute: typeof FinalTestRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  ProgramsRoute: typeof ProgramsRoute
  RegisterRoute: typeof RegisterRoute
  SvedenRoute: typeof SvedenRoute
  TeacherRoute: typeof TeacherRoute
  TestRoute: typeof TestRoute
  TheoryRoute: typeof TheoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theory': {
      id: '/theory'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof TheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sveden': {
      id: '/sveden'
      path: '/sveden'
      fullPath: '/sveden'
      preLoaderRoute: typeof SvedenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final-test': {
      id: '/final-test'
      path: '/final-test'
      fullPath: '/final-test'
      preLoaderRoute: typeof FinalTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AiRoute: AiRoute,
  DocumentsRoute: DocumentsRoute,
  FinalTestRoute: FinalTestRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  ProgramsRoute: ProgramsRoute,
  RegisterRoute: RegisterRoute,
  SvedenRoute: SvedenRoute,
  TeacherRoute: TeacherRoute,
  TestRoute: TestRoute,
  TheoryRoute: TheoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
